name = "Garamon"
uuid = "dbf15181-0796-4f0c-80cc-db9023881340"
authors = ["Jean-François Baffier", "Stéphane Breuils", "Vincent Nozick"]
version = "0.0.1"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
